export const FETCH_BOOKS_REQUEST = "FETCH_BOOKS_REQUEST";
export const FETCH_BOOKS_FAILURE = "FETCH_BOOKS_FAILURE";
export const FETCH_BOOKS_FINALLY = "FETCH_BOOKS_FINALLY";
export const FETCH_BOOKS_SUCCESS = "FETCH_BOOKS_SUCCESS";
export const BOOK_ADDED_TO_CART = "BOOK_ADDED_TO_CART";
export const BOOK_REMOVED_FROM_CART = "BOOK_REMOVED_FROM_CART";
export const BOOK_DELETED_FROM_CART = "BOOK_DELETED_FROM_CART";